### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by dzheltkov** [Donskoy-Andrey/bestway#1]
1) Задание несколько иное, стартовая точка в первой строке и конечная в последней задаются пользователем.

2) У алгоритма несколько проблем:
- Инициализация слишком маленьким числом.
- В целом он устроен неправильно, например, для матрицы вида
```
    1     1     1     1    1
   255   255   255   255   1
    1     1     1     1    1
    1    255   255   255  255
    1     1     1     1    1
```
он найдёт неправильный путь.

3) Потом нужно будет добавить чтение/запись из PNG файла из C++.

**Comment by AndreiDonskoi** [comment]
@dzheltkov, полностью переделал алгоритм на новый вид, используя структуры. Теперь на предложенном примере и на изображениях все работает. 

Также теперь стартовая и конечная точка тоже учитываются, а максимальное изначальное значение в массиве задано максимальным int.

**Comment by dzheltkov** [comment]
Да, теперь всё верно.
Единственное, использовать std::min так как вы его используете не стоит.
То есть, это, по сути, некоторое ветвление, и у вас вместо одного ветвления получается 3 (вы дважды вычисляете std::min и проверка на то, что неравно) вместо одного (а ветвление, в целом, медленнее, чем вычисление). Компилятор, вероятно, соптимизирует это до двух ветвлений, но всё равно хуже, чем одно. Но это замечание не влияет на то, будет ли работа зачтена.

Осталось только разобраться с загрузкой / сохранением PNG из С++.

**Comment by Donskoy-Andrey** [comment]
@dzheltkov

**Comment by AndreiDonskoi** [comment]
@dzheltkov, обновил репозиторий загрузкой и сохранением PNG функциями в С++. Результат - 3 изображение в readme.

**Comment by dzheltkov** [comment]
Задание зачтено.
